import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:callbreak/engine/card.dart';
import 'package:callbreak/engine/game.dart';
import 'package:callbreak/engine/rules.dart';

/// The client and the Go server in `backend/` are two implementations of one
/// protocol, and nothing in either language's type system connects them. This
/// test closes that gap: it decodes bytes the *real* server produced.
///
/// The fixtures are generated by `backend/internal/engine/golden_test.go`. If
/// the server's encoding changes, the Go test fails first with instructions to
/// regenerate; then this test says whether the client can still read the
/// result. Fixing a failure here means fixing a real incompatibility, never the
/// fixture.
void main() {
  final fixtures = File('../backend/testdata/view_frames.json');

  group('server view frames decode', () {
    late Map<String, dynamic> frames;

    setUpAll(() {
      if (!fixtures.existsSync()) {
        fail(
          'Missing ${fixtures.path}. Generate it with:\n'
          '  cd backend && UPDATE_GOLDEN=1 ./scripts/go.sh test ./internal/engine',
        );
      }
      frames = Map<String, dynamic>.from(jsonDecode(fixtures.readAsStringSync()) as Map);
    });

    test('every phase the server can send is decodable', () {
      expect(
        frames.keys,
        containsAll(<String>[
          'bidding',
          'playing',
          'trickComplete',
          'handOver',
          'gameOver',
          'spectator',
          'withTurnClock',
        ]),
      );

      for (final entry in frames.entries) {
        final message = Map<String, dynamic>.from(entry.value as Map);
        expect(
          message['type'],
          'view',
          reason: '${entry.key} must arrive as a view frame',
        );

        // The real decode path: RemoteSession hands the whole message straight
        // to GameView.fromJson, so anything that throws here would throw on a
        // player's phone.
        final view = GameView.fromJson(message);

        expect(view.players, hasLength(4), reason: entry.key);
        expect(view.handCounts, hasLength(4), reason: entry.key);
        expect(view.bids, hasLength(4), reason: entry.key);
        expect(view.tricksWon, hasLength(4), reason: entry.key);
        expect(view.totals, hasLength(4), reason: entry.key);
        expect(view.roundScores, hasLength(4), reason: entry.key);
        expect(view.handsPerGame, handsPerGame, reason: entry.key);
      }
    });

    test('a seat sees its own cards and nobody else\'s', () {
      final view = GameView.fromJson(Map<String, dynamic>.from(frames['bidding'] as Map));

      expect(view.you, 0);
      expect(view.hand, hasLength(13));
      expect(view.handCounts, [13, 13, 13, 13]);
      expect(view.phase, GamePhase.bidding);
      // Nothing has been bid yet, and nulls must survive the crossing rather
      // than arriving as zeros.
      expect(view.bids, everyElement(isNull));
      expect(view.lastTrick, isNull);
      expect(view.turn, isNotNull);
    });

    test('a spectator frame carries no cards at all', () {
      final view = GameView.fromJson(
        Map<String, dynamic>.from(frames['spectator'] as Map),
      );
      expect(view.you, isNull);
      expect(view.hand, isEmpty);
      expect(view.legalMoveIds, isEmpty);
    });

    test('a completed trick round-trips with its winner', () {
      final view = GameView.fromJson(
        Map<String, dynamic>.from(frames['trickComplete'] as Map),
      );

      expect(view.awaitingTrickClear, isTrue);
      expect(view.lastTrick, isNotNull);
      expect(view.lastTrick!.plays, hasLength(4));
      expect(
        view.lastTrick!.winner,
        trickWinner(view.lastTrick!.plays),
        reason: 'the server and the client must agree on who took the trick',
      );
      // Nobody is on the clock while a finished trick is on the table.
      expect(view.turn, isNull);
    });

    test('scores survive the crossing exactly, decimals and all', () {
      final view = GameView.fromJson(
        Map<String, dynamic>.from(frames['gameOver'] as Map),
      );

      expect(view.phase, GamePhase.gameOver);
      expect(view.rankings, hasLength(4));
      expect(view.rankings.map((r) => r.seat).toSet(), {0, 1, 2, 3});

      for (var seat = 0; seat < 4; seat++) {
        expect(view.roundScores[seat], hasLength(handsPerGame));

        // Dart and Go round scores identically — `(x * 10).round() / 10` and
        // math.Round both go half away from zero — so the totals the server
        // computed must equal the ones this client would.
        final expected = view.roundScores[seat].fold<double>(
          0,
          (running, delta) => ((running + delta) * 10).round() / 10,
        );
        expect(
          view.totals[seat],
          closeTo(expected, 1e-9),
          reason: 'seat $seat total disagrees with the sum of its rounds',
        );
      }
    });

    test('turn clocks arrive as a future deadline against server time', () {
      final view = GameView.fromJson(
        Map<String, dynamic>.from(frames['withTurnClock'] as Map),
      );

      expect(view.turnDeadlineMs, greaterThan(0));
      expect(view.serverTimeMs, greaterThan(0));
      expect(view.secondsLeft, 15);
    });

    test('older frames without the server-only fields still decode', () {
      // Turn clocks are additive; a client must not require them, because a
      // locally hosted LAN table never sends them.
      final message = Map<String, dynamic>.from(frames['playing'] as Map)
        ..remove('turnDeadlineMs')
        ..remove('serverTimeMs');

      final view = GameView.fromJson(message);
      expect(view.turnDeadlineMs, 0);
      expect(view.secondsLeft, isNull);
    });

    test('card ids mean the same thing on both sides', () {
      final view = GameView.fromJson(Map<String, dynamic>.from(frames['bidding'] as Map));

      // Re-encoding a card the server sent must reproduce the server's id, or
      // every `play` frame this client sends would name a different card.
      for (final card in view.hand) {
        expect(PlayingCard.fromId(card.id), card);
      }
      // The hand is a legal 13-card deal: no duplicates, all real cards.
      expect(view.hand.toSet(), hasLength(13));
      expect(view.hand.every(fullDeck().contains), isTrue);
    });
  });
}
